### ISSUE TITLE
YOLOv5 weights files not in repository

### ISSUE THREAD

**Issue by nomelab** [rperera12/MachineLearning_Framework_Microstructure_Characterization#1]
Note, your current Github does not include the trained weights file as described in the readme.

**Comment by rperera12** [comment]
Hi,
In the Readme file, in Section "Pretrained Models/Weights" I explain that all the pretrained weights (including YOLOv5 weights) can be found at this google drive: 

Link:  https://drive.google.com/drive/folders/1QebmbTBFOvzmRISkUmkYTzFiQEpCnbsD

Please note that due to the large size of the .pth saved weights, I could not upload the pretrained weights to this specific GitHub repo. Refer to the attached link.

**Comment by edgmin** [comment]
Hello,

First of all, thank you for making the code available!

I have a question regarding the preparation of the GB dataset. You mentioned that high resolution images were resized from 2048x1532 to 2048x2048. How did you do that? Did you replicate any part of the image?

Thank you in advance!
